package project;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class project1 extends javax.swing.JFrame 
{
    DefaultTableModel model;
    static DefaultListModel l;
    String Delete[] ={""};
    public project1() 
    {
        this.model = new DefaultTableModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelZone1 = new javax.swing.JPanel();
        jBtnZone = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        zoneList = new javax.swing.JList<>();
        jPanelBtn = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelDispRule = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnAddRule = new javax.swing.JButton();
        jBtnDeleteRule = new javax.swing.JButton();
        jBtngetRule = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Frame");

        jPanelZone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtnZone.setText("Zone");
        jBtnZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZoneActionPerformed(evt);
            }
        });

        zoneList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zoneList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                zoneListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(zoneList);

        javax.swing.GroupLayout jPanelZone1Layout = new javax.swing.GroupLayout(jPanelZone1);
        jPanelZone1.setLayout(jPanelZone1Layout);
        jPanelZone1Layout.setHorizontalGroup(
            jPanelZone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZone1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnZone, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanelZone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelZone1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelZone1Layout.setVerticalGroup(
            jPanelZone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZone1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnZone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelZone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelZone1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        jPanelBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Disable");

        jButton2.setText("Enable");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnLayout = new javax.swing.GroupLayout(jPanelBtn);
        jPanelBtn.setLayout(jPanelBtnLayout);
        jPanelBtnLayout.setHorizontalGroup(
            jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBtnLayout.setVerticalGroup(
            jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelDispRule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Display All Rules");

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Source IP", "Destination IP", "Port", "Policy", "Protocol", "Target"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jBtnAddRule.setText("+");
        jBtnAddRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddRuleActionPerformed(evt);
            }
        });

        jBtnDeleteRule.setText("--");
        jBtnDeleteRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteRuleActionPerformed(evt);
            }
        });

        jBtngetRule.setText("Get Rules");
        jBtngetRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtngetRuleActionPerformed(evt);
            }
        });

        jBtnClose.setText("Close");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDispRuleLayout = new javax.swing.GroupLayout(jPanelDispRule);
        jPanelDispRule.setLayout(jPanelDispRuleLayout);
        jPanelDispRuleLayout.setHorizontalGroup(
            jPanelDispRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDispRuleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDispRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(jPanelDispRuleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBtnAddRule, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDeleteRule, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtngetRule, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDispRuleLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDispRuleLayout.setVerticalGroup(
            jPanelDispRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDispRuleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDispRuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddRule, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDeleteRule, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtngetRule, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenu1.setText("Packet");

        jMenuItem1.setText("Packet Filter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Port");

        jMenuItem2.setText("Port Moniter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logs");

        jMenuItem3.setText("All System Logs");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Rules History");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelZone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDispRule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDispRule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelZone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZoneActionPerformed
        AZONES z = new AZONES();
        z.setVisible(true);
        z.AL();
        z.AL1();
        z.setLocation(200, 150);
    }//GEN-LAST:event_jBtnZoneActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PacketFilter pkf = new PacketFilter();
        pkf.setVisible(true);
        pkf.setLocation(200, 150);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBtnAddRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddRuleActionPerformed
        String zone = ClientLogBean.getZone();
        if(zone == null)
        {
            Rules.infoBox("Please Select Zone", "Select Zone");
        }
        else
        {
            NewAddRules ar = new NewAddRules();
            ar.setVisible(true);
            ar.setLocation(200, 150);
        }
    }//GEN-LAST:event_jBtnAddRuleActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ScanPort sp = new ScanPort();
        sp.setVisible(true);
        sp.setLocation(200, 150);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBtngetRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtngetRuleActionPerformed
        try 
        {
            setData();
        } 
        catch (IOException ex) 
        {
           // Logger.getLogger(NewApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtngetRuleActionPerformed

    private void zoneListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_zoneListValueChanged
        ClientLogBean.setZone(zoneList.getSelectedValue());
    }//GEN-LAST:event_zoneListValueChanged

    private void jBtnDeleteRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteRuleActionPerformed
        String zone = ClientLogBean.getZone();
        String user = ClientLogBean.getUser();
        if(zone == null)
        {
            Rules.infoBox("Please Select Zone", "Select Zone");
        }
        else
        {
            int raw = jTable1.getSelectedRow();
            System.out.println("raw --------------->"+raw);
            ArrayList fileRule = FileOpeartionNew.ReadFile(zone+"/SysActiveLogs");
            ArrayList clfileRule = FileOpeartionNew.ReadFile(zone+"/ClientActiveLogs");
            ArrayList fileRule1 = null;
            String filerule = (String) fileRule.get(raw);
            String clfilerule = (String) clfileRule.get(raw);
            String[] cldelRule = clfilerule.split("\t");
            String cldelRule1 = "";
            for(int i = 1; i < cldelRule.length; i++)
            {
                cldelRule1 = cldelRule1 + cldelRule[i] + "\t";
            }
//            System.out.println("rule------------------>"+rule);
            String[] rule = filerule.split("\t");
//            System.out.println(rule[1]);
            String[] disRuleSplit = rule[1].split(" ");
            disRuleSplit[2] = "-D";
            
            int size = disRuleSplit.length;
            String delRule = "";
            for(int i = 0; i < size; i++)
            {
                delRule = delRule + " " + disRuleSplit[i];
            }
            System.out.println("delRule ------------------>"+delRule);
            try {
                Rules.runCmd(delRule);
            } catch (IOException ex) {
                Logger.getLogger(project1.class.getName()).log(Level.SEVERE, null, ex);
            }
            try 
            {
                LogManager.WriteSysDisLog(delRule);
                LogManager.WriteClintDisLog(cldelRule1);
            }
            catch (IOException ex) 
            {
                Logger.getLogger(project1.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("raw ---------------->"+raw);
            fileRule.remove(raw);
            clfileRule.remove(raw);
            System.out.println("fileRules ----------->"+fileRule);
           
            
            LogManager.DeleteData(fileRule,"SysActiveLogs");
            LogManager.DeleteData(clfileRule,"ClientActiveLogs");
            
        }
        
        try {
            setData();
        } catch (IOException ex) {
            Logger.getLogger(project1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnDeleteRuleActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ruleHistory rh = new ruleHistory();
        rh.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                project1 p = new project1();
                p.setVisible(true);
                p.setLocation(250, 150);
                p.setBackground(Color.red);
                p.AL();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddRule;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnDeleteRule;
    private javax.swing.JButton jBtnZone;
    private javax.swing.JButton jBtngetRule;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanelBtn;
    private javax.swing.JPanel jPanelDispRule;
    private javax.swing.JPanel jPanelZone1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private static javax.swing.JList<String> zoneList;
    // End of variables declaration//GEN-END:variables

    public void setData() throws IOException 
    {
        int col = -1;
        int raw = model.getRowCount();
        String user = ClientLogBean.getUser();
//        String[] str1 = {"INPUT", "FORWARD", "OUTPUT"};
        System.out.println(raw);
//        if (raw >= 1) 
//        {
//            for (int i = raw - 1; i >= 0; i--) 
//            {
//                model.removeRow(i);
//            }
//        }
       // Process p1 = Runtime.getRuntime().exec("sudo iptables -L -n -v");
       String zone = ClientLogBean.getZone();
        System.out.println("ZONE ---------------->"+zone);
       if(zone == null)
       {
           Rules.infoBox("Please Select Zone First", "Select Zone");
       }
        else 
       {
            BufferedReader stdInput = new BufferedReader(new InputStreamReader(new FileInputStream("/home/"+user+"/FireShark/ZoneName/"+zone+"/ClientActiveLogs.txt")));
//            BufferedReader stdError = new BufferedReader(new InputStreamReader(new FileInputStream("/home/"+user+"/FireShark/ZoneName/"+zone+"/ClientActiveLogs.txt")));
            String s = null;
            String s1 = "";
            model = (DefaultTableModel) jTable1.getModel();
            int b = model.getRowCount();
            System.out.println("Row Count ------------->"+b);
            for(int i = b-1; i >= 0; i--)
            {
                model.removeRow(i);
            }

            while ((s = stdInput.readLine()) != null) 
            {
                String[] str = s.split("\t"); // Ex -> [a-zA-Z0-9][ *,\t][a-zA-Z_0-9/.]
                System.out.println(str);
                ArrayList<String> nums = new ArrayList<String>();
                System.out.println(nums);
                int a = str.length;
                
                
                for (int i = 2; i < a; i++) 
                {
                    nums.add(str[i]);
                }
                // nums.add(str1[col]);
                str = nums.toArray(new String[0]);
                model.addRow(str);
            }
//            raw++;
            jTable1.setModel(model);
        }
    }
    
    static void AL() 
    {
        ArrayList<String> listOfLines = FileOpeartionNew.ReadFile("ZoneMain/ZoneMain");
        l = new DefaultListModel();
        int size = listOfLines.size();
        for (int i = 0; i < size; i++) 
        {
           // System.out.println("**" + i);
            if (listOfLines.get(i).equals("")) 
            {
                System.out.println("hello......................");
            }
            else 
            {
                l.addElement(listOfLines.get(i));
            }
        }
        System.out.println("Done");
        zoneList.setModel(l);
    }
}